#!/usr/bin/env bash
set -e
function info { echo -e "\e[32m[info] $*\e[39m"; }
function warn  { echo -e "\e[33m[warn] $*\e[39m"; }
function error { echo -e "\e[31m[error] $*\e[39m"; exit 1; }
. /usr/share/debconf/confmodule
ARCH=$(uname -m)

BINARY_DOCKER=/usr/bin/docker

DOCKER_REPO="homeassistant"

SERVICE_DOCKER="docker.service"
SERVICE_NM="NetworkManager.service"

# Read infos from web
URL_CHECK_ONLINE="baidu.com"
URL_VERSION="https://version.home-assistant.io/stable.json"
HASSIO_VERSION=$(curl -s ${URL_VERSION} | jq -e -r '.supervisor')
URL_APPARMOR_PROFILE="https://version.home-assistant.io/apparmor.txt"


# Restart NetworkManager
info "正在重启 NetworkManager"
systemctl restart "${SERVICE_NM}"

# Enable and start systemd-resolved
if [ "$(systemctl is-active systemd-resolved)" = 'inactive' ]; then
    info "启用 systemd-resolved"
    systemctl enable systemd-resolved.service> /dev/null 2>&1;
    systemctl start systemd-resolved.service> /dev/null 2>&1;
fi

# Check and fix systemd-journal-gatewayd socket location
if [ ! -S "/run/systemd-journal-gatewayd.sock" ]; then
    info "设置 systemd-journal-gatewayd socket文件"
    if [ "$(systemctl is-active systemd-journal-gatewayd.socket)" = 'active' ]; then
        systemctl stop systemd-journal-gatewayd.socket> /dev/null 2>&1;
    fi
    rm -rf "/run/systemd-journal-gatewayd.sock";
fi
# Enable and start systemd-journal-gatewayd
if [ "$(systemctl is-active systemd-journal-gatewayd.socket)" = 'inactive' ]; then
    info "启用 systemd-journal-gatewayd"
    systemctl enable systemd-journal-gatewayd.socket> /dev/null 2>&1;
    systemctl start systemd-journal-gatewayd.socket> /dev/null 2>&1;
fi

# Restart Docker service
info "重启docker服务"
systemctl restart "${SERVICE_DOCKER}"

# Check network connection
while ! ping -c 1 -W 1 ${URL_CHECK_ONLINE}; do
    info "无法Ping通 ${URL_CHECK_ONLINE} - 网络接口可能已关闭…"
    sleep 2
done

# Get primary network interface
PRIMARY_INTERFACE=$(ip route | awk '/^default/ { print $5; exit }')
IP_ADDRESS=$(ip -4 addr show dev "${PRIMARY_INTERFACE}" | awk '/inet / { sub("/.*", "", $2); print $2 }')

case ${ARCH} in
    "i386" | "i686")
        MACHINE=${MACHINE:=qemux86}
        HASSIO_DOCKER="${DOCKER_REPO}/i386-hassio-supervisor"
    ;;
    "x86_64")
        MACHINE=${MACHINE:=qemux86-64}
        HASSIO_DOCKER="${DOCKER_REPO}/amd64-hassio-supervisor"
    ;;
    "arm" |"armv6l")
        if [ -z "${MACHINE}" ]; then
             db_input critical ha/machine-type || true
             db_go || true
             db_get ha/machine-type || true
             MACHINE="${RET}"
             db_stop
        fi
        HASSIO_DOCKER="${DOCKER_REPO}/armhf-hassio-supervisor"
    ;;
    "armv7l")
        if [ -z "${MACHINE}" ]; then
             db_input critical ha/machine-type || true
             db_go || true
             db_get ha/machine-type || true
             MACHINE="${RET}"
             db_stop
        fi
        HASSIO_DOCKER="${DOCKER_REPO}/armv7-hassio-supervisor"
    ;;
    "aarch64")
        if [ -z "${MACHINE}" ]; then
             db_input critical ha/machine-type || true
             db_go || true
             db_get ha/machine-type || true
             MACHINE="${RET}"
             db_stop

        fi
        HASSIO_DOCKER="${DOCKER_REPO}/aarch64-hassio-supervisor"
    ;;
    *)
        error "${ARCH} 未知!"
    ;;
esac
PREFIX=${PREFIX:-/usr}
SYSCONFDIR=${SYSCONFDIR:-/etc}
DATA_SHARE=${DATA_SHARE:-/home/hassio}
CONFIG="${SYSCONFDIR}/hassio.json"
cat > "${CONFIG}" <<- EOF
{
    "supervisor": "${HASSIO_DOCKER}",
    "machine": "${MACHINE}",
    "data": "${DATA_SHARE}"
}
EOF


# Install Supervisor
info "安装 Supervisor 启动脚本"
sed -i "s,%%HASSIO_CONFIG%%,${CONFIG},g" "${PREFIX}"/sbin/hassio-supervisor
sed -i -e "s,%%BINARY_DOCKER%%,${BINARY_DOCKER},g" \
       -e "s,%%SERVICE_DOCKER%%,${SERVICE_DOCKER},g" \
       -e "s,%%BINARY_HASSIO%%,${PREFIX}/sbin/hassio-supervisor,g" \
       "${SYSCONFDIR}/systemd/system/hassio-supervisor.service"

chmod a+x "${PREFIX}/sbin/hassio-supervisor"
systemctl enable hassio-supervisor.service > /dev/null 2>&1;

# Install AppArmor
info "安装 AppArmor 脚本"
mkdir -p "${DATA_SHARE}/apparmor"
curl -sL ${URL_APPARMOR_PROFILE} > "${DATA_SHARE}/apparmor/hassio-supervisor"
sed -i "s,%%HASSIO_CONFIG%%,${CONFIG},g" "${PREFIX}/sbin/hassio-apparmor"
sed -i -e "s,%%SERVICE_DOCKER%%,${SERVICE_DOCKER},g" \
    -e "s,%%HASSIO_APPARMOR_BINARY%%,${PREFIX}/sbin/hassio-apparmor,g" \
    "${SYSCONFDIR}/systemd/system/hassio-apparmor.service"

chmod a+x "${PREFIX}/sbin/hassio-apparmor"
systemctl enable hassio-apparmor.service > /dev/null 2>&1;
systemctl start hassio-apparmor.service

# Start Supervisor
info "启动 Home Assistant Supervised"
systemctl start hassio-supervisor.service

# Install HA CLI
info "安装 ha 命令行界面"
chmod a+x "${PREFIX}/bin/ha"

# Switch to cgroup v1
if [ -f /etc/default/grub ]
then
    if ! grep -q "systemd.unified_cgroup_hierarchy=false" /etc/default/grub; then
        info "切换到 cgroup v1"
        cp /etc/default/grub /etc/default/grub.bak
        sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT="/&systemd.unified_cgroup_hierarchy=false /' /etc/default/grub
        update-grub
        touch /var/run/reboot-required
    fi
elif [ -f /boot/firmware/cmdline.txt ]
then
    if ! grep -q "systemd.unified_cgroup_hierarchy=false" /boot/firmware/cmdline.txt; then
        info "切换到 cgroup v1"
        sed -i.bak 's/$/ systemd.unified_cgroup_hierarchy=false/' /boot/firmware/cmdline.txt
        touch /var/run/reboot-required
    fi
else
    warn "无法找到 /etc/default/grub 或 /boot/firmware/cmdline.txt，无法切换到 cgroup v1"
fi
info "在几分钟内，您将能够访问 Home Assistant，网址为："
info "http://homeassistant.local:8123 或使用您的 IP 地址"
info "机器的 IP 地址为: http://${IP_ADDRESS}:8123"
if [ -f /var/run/reboot-required ]
then
    warn "需要重新启动系统以应用对 grub 的更改"
fi
